# ~/Documents/Plone/volto/manifests/ingress.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: volto-frontend-ingress
  namespace: plone
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Host $host;
spec:
  rules:
  - host: volto.club-linux.ch  # <--- Assure-toi d'utiliser cet hôte pour Volto
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-plone-frontend # <--- Le service Volto
            port:
              number: 3000
